[project]
name = "dublar-worker"
version = "0.1.0"
description = "Worker para processamento de áudio com dublagem"
requires-python = ">=3.9"
dependencies = [
    "kafka-python==2.2.15",
    "tensorflow-cpu==2.15.0",
    "requests==2.32.4",
    "ffmpeg-python==0.2.0",
    "typer==0.3.2",
    "spleeter==2.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["deps", "engines", "handlers", "clients", "errors", "routes"]
